const apartment = [
    {
        'id' : 0,
        'name' : 'Washington Avenue',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/WgRdY6h/washington.jpg',
        'price': '$194',
        'rent':'550 ',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'     
    },
    {
        'id' : 1,
        'name' : 'Family Apartment Three',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/n7r1Wk0/family.jpg',
        'price': '$356',
        'rent':'',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'     
    },
    {
        'id' : 2,
        'name' : 'Gorgeous house ',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/txFfpzP/gorgeous.jpg',
        'price': '256',
        'rent':'',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'       
    },
    {
        'id' : 3,
        'name' : 'Luxury villa ',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/CVqD88v/luxury.jpg',
        'price': '$345',
        'rent':'',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'        
    },
    {
        'id' : 4,
        'name' : 'Epic Huda Palacio',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/5Wh3Q4H/palacio.jpg',
        'price': '$536',
        'rent':'',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'        
    },
    {
        'id' : 5,
        'name' : 'Washington Avenue',
        'address': 'Nasirabad H/S, Chattogram',
        'img' : 'https://i.ibb.co/HtxnRBw/avenue.jpg',
        'price': '$283',
        'rent':'',
        'serviceCharge':'5,000/= Tk per month', 
        'sequrityDeposit':'3 months rent',
        'feature':'3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        'flatSize':'300 sq feet',
        'floor':'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'roomCategory':'3 Large Bed Rooms with 3 Verandas, Spacious,Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        'facilities':'1 Modern Lift, All Modern Amenities & Semi Furnished.', 
        'addFacilities': 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility'         
    },
    // {
    //     'id' : '',
    //     'name' : '',
    //     'address': '',
    //     'bed':'',
    //     'bath':'',
    //     'img' : '',
    //     'price': '',
    //     'homeDetails': '',
    //     'rent':'',
    //     'charge':'',
    //     'sequrity':'',
    //     'policy':'',
    //     'propertyDetails':''
    // },
      
]
export default apartment;
